/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f446xx.h"
#include <stdio.h>
#include <stdint.h>

#define APP_BASE    0x08020000UL
#define SRAM_START  0x20000000UL
#define SRAM_END    0x20020000UL


static void delay_ms(uint32_t ms){
	for(uint32_t i = 0;i < ms*1600; i++){
		__NOP();
	}
}

static void init_led(){
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER &= ~(3U << 10);
	GPIOA->MODER |= (1U << 10);
}

static void Gpio_on(){
	GPIOA->BSRR |= (1U << 5);
}

static void Gpio_off(){
	GPIOA->BSRR |= ((1U << 5)<<16);
}

static void no_app_forever(){
	while(1){
		Gpio_on();
		delay_ms(80);

		Gpio_off();
		delay_ms(80);
	}
}

static void deinit(){
	__disable_irq();

	for(uint16_t i=0;i < 8 ; i++){
		NVIC->ICER[i] = 0xFFFFFFFFUL;     //dis all intrrupt
		NVIC->ICPR[i] = 0xFFFFFFFFUL;	//remove all pending state
	}

	SysTick->CTRL = 0;
	SysTick->LOAD = 0;
	SysTick->VAL = 0;

	RCC->AHB1RSTR |= RCC_AHB1RSTR_GPIOARST;
	RCC->AHB1RSTR &= ~RCC_AHB1RSTR_GPIOARST;
	RCC->AHB1ENR &= ~RCC_AHB1ENR_GPIOAEN;

}

__attribute__((naked)) void jump_to_app(uint32_t app_sp , uint32_t app_pc){
	__asm volatile (
			"msr MSP,r0 \n"
			"bx r1	\n"

	);
}

int main(void){

	uint32_t app_sp, app_pc;

	init_led();

	Gpio_on();
	delay_ms(1000);


	Gpio_off();
	delay_ms(1000);

	app_sp = *(volatile uint32_t *)APP_BASE;

	if(app_sp < SRAM_START ||  app_sp > SRAM_END){
		no_app_forever();
	}

	app_pc =*(volatile uint32_t *)(APP_BASE + 4U);

	deinit();

	SCB->VTOR = APP_BASE;
	__enable_irq();

	jump_to_app(app_sp,app_pc);

	while(1){}


}


